# Generated by Django 2.2.1 on 2019-10-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='term',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
